module.exports = {
  Easy: [
    { id: 1, q: "The sum of 2 and 3 equals 5.", a: "True" },
    { id: 2, q: "If you subtract 2 from 5, the result is 4.", a: "False" },
    { id: 3, q: "Dividing 10 by 2 gives 5.", a: "True" },
    { id: 4, q: "Seven minus three equals four.", a: "True" },
    { id: 5, q: "Multiplying 4 by 2 results in 9.", a: "False" },
    { id: 6, q: "Adding 9 and 1 gives 10.", a: "True" },
    { id: 7, q: "The sum of 5 and 3 equals 7.", a: "False" },
    { id: 8, q: "Dividing 6 by 3 results in 2.", a: "True" },
    { id: 9, q: "Subtracting 5 from 8 equals 2.", a: "False" },
    { id: 10, q: "The product of 3 and 3 is 9.", a: "True" },
    { id: 11, q: "Multiplying 2 by 2 equals 5.", a: "False" },
    { id: 12, q: "Adding 1 and 1 gives 2.", a: "True" },
    { id: 13, q: "The sum of 0 and 0 equals 1.", a: "False" },
    { id: 14, q: "Seven minus four equals three.", a: "True" },
    { id: 15, q: "Multiplying 5 by 1 results in 5.", a: "True" },
    { id: 16, q: "Dividing 6 by 2 gives 4.", a: "False" },
    { id: 17, q: "The difference between 10 and 7 is 3.", a: "True" },
    { id: 18, q: "The sum of 3 and 3 equals 7.", a: "False" },
    { id: 19, q: "Multiplying 4 by 2 equals 8.", a: "True" },
    { id: 20, q: "Dividing 9 by 3 gives 4.", a: "False" }
  ],

  Medium: [
    { id: 21, q: "If x equals 2, then 2x plus 3 equals 7.", a: "True" },
    { id: 22, q: "If x equals 3, then 3x minus 4 equals 5.", a: "False" },
    { id: 23, q: "When y equals 2, adding 4y and 1 results in 9.", a: "True" },
    { id: 24, q: "If x equals 3, subtracting 2 from 5x gives 12.", a: "False" },
    { id: 25, q: "If x equals 6, dividing x by 2 gives 3.", a: "True" },
    { id: 26, q: "If x equals 3, adding 2 times x to 7 equals 10.", a: "False" },
    { id: 27, q: "When x is 3, multiplying the sum of x and 2 by 3 results in 15.", a: "True" },
    { id: 28, q: "If x equals 5, subtracting x from 5 gives 1.", a: "False" },
    { id: 29, q: "Multiplying 6 by 2 equals 12.", a: "True" },
    { id: 30, q: "Dividing 9 by 3 results in 4.", a: "False" },
    { id: 31, q: "The square root of 16 equals 4.", a: "True" },
    { id: 32, q: "Dividing 10 by 2 gives 6.", a: "False" },
    { id: 33, q: "If x equals 1, then 2x plus 3 equals 7.", a: "False" },
    { id: 34, q: "The sum of the angles in a triangle equals 180 degrees.", a: "True" },
    { id: 35, q: "If x equals 4, multiplying 5 by x results in 25.", a: "False" },
    { id: 36, q: "The number 0 is considered an even number.", a: "True" },
    { id: 37, q: "Adding 2 and 2 gives 5.", a: "False" },
    { id: 38, q: "The sum of 9 and 3 equals 12.", a: "True" },
    { id: 39, q: "The number 7 is a multiple of 3.", a: "False" },
    { id: 40, q: "Multiplying 1 by 1 equals 1.", a: "True" }
  ],

  Hard: [
    { id: 41, q: "If x equals 2, then 2 times the sum of x and 3 equals 10.", a: "False" },
    { id: 42, q: "If x equals 2, then 5x minus 2 equals 8.", a: "True" },
    { id: 43, q: "The square root of 2 is a rational number.", a: "False" },
    { id: 44, q: "Adding 4 to the product of 3 and 3 equals 13.", a: "True" },
    { id: 45, q: "If x equals 3, then 4x minus 5 equals 7.", a: "True" },
    { id: 46, q: "If x equals 3, then 7x plus 2 equals 23.", a: "False" },
    { id: 47, q: "Dividing 10 by 2 results in 5.", a: "True" },
    { id: 48, q: "The square of 6 equals 35.", a: "False" },
    { id: 49, q: "If x equals 3, then 5 times the sum of x and 1 equals 20.", a: "True" },
    { id: 50, q: "The sum of the first five odd numbers equals 25.", a: "True" },
    { id: 51, q: "Dividing 15 by 3 gives 6.", a: "False" },
    { id: 52, q: "Adding 9 and 10 equals 19.", a: "True" },
    { id: 53, q: "Multiplying a number by 1 changes its value.", a: "False" },
    { id: 54, q: "Zero is a prime number.", a: "False" },
    { id: 55, q: "The square root of 49 equals 7.", a: "True" },
    { id: 56, q: "Subtracting 5 from 11 gives 6.", a: "True" },
    { id: 57, q: "If x equals 2, then 2x plus 5 equals 11.", a: "True" },
    { id: 58, q: "Dividing 10 by 2 equals 6.", a: "False" },
    { id: 59, q: "Multiplying 3 by 4 equals 12.", a: "True" },
    { id: 60, q: "The square of 5 equals 30.", a: "False" }
  ]
};
